src/home/urls.py
from django.urls import  path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
]

src/location/urls.py
from django.urls import  path
from . import views

app_name = "location"
urlpatterns = [
    path("", views.index, name="index"),
]

src/savour-pinoy-sushi/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Savour Pinoy & Sushi Administration"

urlpatterns = [
    path("", include("home.urls")),
    path("menu/", include("menu.urls")),
    path("location/", include("location.urls")),
    path("admin/", admin.site.urls),
]

# serves user-uploaded media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/savoy/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Savour Pinoy & Sushi Administration"

urlpatterns = [
    path("", include("home.urls")),
    path("menu/", include("menu.urls")),
    path("location/", include("location.urls")),
    path("admin/", admin.site.urls),
]

# serves user-uploaded media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/home/models.py
from django.db import models

# Create your models here.

src/location/models.py
from datetime import date, timedelta
from django.db import models


class LocationSetting(models.Model):

    # number of days to display in the past
    display_days_back = models.IntegerField()

    def __str__(self):
        return 'Location Settings'

class LocationDestination(models.Model):
    # the location's name on the website
    display_txt = models.CharField(max_length=100)

    # the location's address on the website
    addr_txt = models.CharField(max_length=200)

    def __str__(self):
        return self.display_txt


class LocationStop(models.Model):
    # when the truck will be at this location
    stop_dt = models.DateField()

    # the hours that the food truck is at this stop
    hours_txt = models.CharField(max_length=100)

    # where the truck will be located
    location = models.ForeignKey(LocationDestination, on_delete=models.CASCADE)

    def filtered_by_days_back(self):
        settings = LocationSetting.objects.first()
        days_back = date.today() - timedelta(days=settings.display_days_back)
        return self.stop_dt >= days_back

    def __str__(self):
        return f"{str(self.location)} on {self.stop_dt}"

src/menu/models.py
from django.db import models

class MenuSection(models.Model):

    # the section's name on the website
    display_txt = models.CharField(max_length=100)

    # a description or notes about the section
    desc_txt = models.CharField(max_length=200)

    # does the raw food disclaimer apply
    raw_disclaimer = models.BooleanField()

    def __str__(self):
        return self.display_txt

class MenuItem(models.Model):
    # the item's name on the website
    display_txt = models.CharField(max_length=100)

    # a description or notes about the item
    desc_txt = models.CharField(max_length=200, null=True)

    # the current price of the item
    price = models.DecimalField(max_digits=5, decimal_places=2)

    # does the raw food disclaimer apply
    raw_disclaimer = models.BooleanField(default=False)

    # the section under which this item appears
    section = models.ForeignKey(MenuSection, on_delete=models.CASCADE)

    # an optional image of the menu item
    image = models.ImageField(upload_to='menu_images/', null=True)

    def __str__(self):
        return self.display_txt

src/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "home/index.html")

src/location/views.py
from datetime import date, timedelta
from django.shortcuts import render
from .models import LocationStop, LocationSetting


# Create your views here.
def index(request):
    settings = LocationSetting.objects.first()
    days_back = str(date.today() - timedelta(days=settings.display_days_back))
    location_locationstops = (LocationStop.objects
                              .filter(stop_dt__gte=days_back)
                              .order_by("-stop_dt"))
    stops = []
    for stop in location_locationstops:
        stops.append({ "date": stop.stop_dt.strftime("%A, %d %b"), "hours": stop.hours_txt, "location": stop.location.display_txt, "address": stop.location.addr_txt })

    print(location_locationstops)
    print(stops)

    context = {"stops": stops }
    return render(request, "locations/index.html", context)

src/menu/views.py
from django.shortcuts import render
from .models import MenuSection

# Create your views here.

def index(request):
    menu_sections = MenuSection.objects.all()
    context = {"menu_sections": menu_sections}
    return render(request, "menu/index.html", context)

src/home/templates/base/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us" dir="ltr">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Savour Pinoy & Sushi</title>

  <!-- TODO: add favicon -->
  <link rel="shortcut icon" href="" />

	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	{% block head %}{% endblock %}
</head>

<header class="wrapper">
	<nav>
		<ul role="list" class="spread compress">
			<li><a href="{% url 'home:index' %}">Home</a></li>
			<li><a href="{% url 'menu:index' %}">Menu</a></li>
			<li><a href="{% url 'location:index' %}">Locations</a></li>
			<li>
				<a href="https://www.facebook.com/savourpinoyandsushi/">
					<img class="icon" src="{% static 'home/images/2021_Facebook_icon.svg' %}" />
				</a>
			</li>
		</ul>
	</nav>
</header>

<main class="flow-l wrapper">
	{% block content %}{% endblock %}
</main>

<footer class="wrapper flow-s">
	<div>
		{% block footer %}{% endblock %}
	</div>
	<ul class="spread-evenly" role="list">
		<li><span>© {% now "Y" %} Savour Pinoy & Sushi, LLC</span></li>
		<li><span>Made with joy by <a href="https://alexbilson.dev">Alex Bilson</a></span></li>
		<li><a href="{% url 'admin:index' %}">Admin</a></li>
	</ul>
</footer>
</html>

src/home/templates/home/index.html
{% extends "base/index.html" %}

{% block content %}
<h1>Welcome to Savour Pinoy & Sushi!</h1>
{% load static %}
<img class="flag" src="{% static 'home/images/Flag_of_the_Philippines.svg' %}" />
{% endblock %}

src/location/templates/locations/index.html
{% extends "base/index.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'location/style.css' %}">
{% endblock %}


{% block content %}
{% if stops %}
	<h2>Stops</h2>
	<ol role="list" class="stops">
		<li>
			<div>Date</div>
			<div>Location</div>
			<div>Address</div>
			<div>Hours</div>
		</li>
	{% for stop in stops %}
		<li>
			<div>{{ stop.date }}</div>
			<div>{{ stop.location }}</div>
			<div>{{ stop.address }}</div>
			<div>{{ stop.hours }}</div>
		</li>
	{% endfor %}
	</ol>
{% else %}
	<p>No stops are available.</p>
{% endif %}
{% endblock %}

src/menu/templates/menu/index.html
{% extends "base/index.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'menu/style.css' %}">
{% endblock %}

{% block content %}
<section class="flow-m | menu">
{% if menu_sections %}
	 {% for section in menu_sections %}
	 <h2>{{ section.display_txt }}{% if section.raw_disclaimer %}<sup>*</sup>{% endif %}</h2>
	 <p class="description">{{ section.desc_txt }}</p>
	 <ul role="list" class="flow-m">
		 {% for item in section.menuitem_set.all %}
		 <li class="spread-between | menu-item">
			 <div>
				 <div class="spread no-wrap"><h3>{{ item.display_txt }}{% if item.raw_disclaimer %}<sup>*</sup>{% endif %}</h3><h4>${{ item.price }}</h4></div>
				 <p class="description">{{ item.desc_txt }}</p>
			 </div>
			 <div>
				 {% if item.image %}
				 <img src="{{ item.image.url }}" />
				 {% endif %}
			 </div>
		 </li>
		 {% endfor %}
	 {% endfor %}
	 </ul>
{% else %}
	 <p>No menu sections are available.</p>
{% endif %}
</section>
{% endblock %}

{% block footer %}
<p>*CONSUMING RAW OR UNDERCOOKED MEATS, POULTRY, SEAFOOD, SHELLFISH, OR EGGS MAY INCREASE YOUR RISK OF FOODBORNE ILLNESS, ESPECIALLY IF YOU HAVE CERTAIN MEDICAL CONDITIONS.</p>
{% endblock %}